name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
        
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build image
        run: docker build -t api-test .
      
      - name: Test container
        run: docker run api-test pytest -vvv

  continuous-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gracia000/sample_api:${{ github.run_number }}
            gracia000/sample_api:latest
